### ISSUE TITLE
License: GPL-2+ or GPL-3+

### ISSUE THREAD

**Issue by andrewshadura** [dictzip/dictzip-java#1]
Hi,

License statements in files state the license of the CLI tool is GPL-2+, but README.md says GPL-3+. Could you please clarify that?

Thanks!

**Comment by miurahr** [comment]
I cannot remember why I  wrote it, but  https://github.com/dictzip/dictzip-java/commit/368e742cda68e7b097a5277756591ba73788d757 does not say anything about reason about license.

It would be wrongly documented in README. (or I might wanted to change it). 

OK, Id like to set GPL2+ here.
